//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project01.Models.DB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class outbond
    {
        
        public outbond()
        {
            this.laporans = new HashSet<laporan>();
        }

        [Key]
    
        public int id_outbond { get; set; }
        public string keterangan { get; set; }
        public int harga { get; set; }
    
        public virtual ICollection<laporan> laporans { get; set; }
    }
}
